### ISSUE TITLE
OpenCV Python with Gstreamer Backend

### ISSUE THREAD

**Issue by stu-github** [ES-Alexander/pythonic-cv#13]
Hi,
From this page, 
https://discuss.bluerobotics.com/t/opencv-python-with-gstreamer-backend/8842
I saw you compiler the opencv-python with gstreamer backend,

I want to study gstreamer just like you, so I need this wheel, could you send me one?

**Comment by ES-Alexander** [comment]
> I want to study gstreamer just like you, so I need this wheel, could you send me one?

OpenCV is a C++ library that needs to be compiled, which means it’s not possible to provide a single wheel that works for everybody because the compilation has to run on the particular hardware and operating system you’re using.

More generally, for gstreamer support to work requires a valid install of gstreamer to be on your computer that OpenCV can link to while it’s building. That’s also not possible to include in a simple wheel.

If you want to use gstreamer with OpenCV you’ll most likely need to do the compilation yourself. You should be able to achieve that by following the steps I provided in the forum post you linked to. As I mentioned there, conveniently the OpenCV-python library does most of the compilation setup for you, so compiling is much simpler to do than it would otherwise normally be.
